# fly.toml app configuration file generated for agro-market-tool-danillo on 2026-08-01T22:27:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agro-market-tool-danillo'
primary_region = 'iad'

[build]

[env]
  DB_PATH = '/data/data.db'

[[mounts]]
  source = 'agro_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
